var TREE_ITEMS = [
['Select A Category', '', {'tt' : 'Select A Category Below', 'sb':'Select A Category','hte':{'oncontextmenu':'return h_context_menu_root(o_tree_item)','style':'color:black'}},
['&#1061;&#1101;&#1083;&#1093;&#1101;&#1101; (0)', 'http://localhost/Photostore/website/gallery.php?gid=53',,],
['&1057&1091&1075&1072 (1)', 'http://localhost/Photostore/website/gallery.php?gid=52',,],
['Sample Private Gallery (0)', 'http://localhost/Photostore/website/pri.php?gid=51&gal=w65z1som',,],
['Art photos for Jane Doe (1)', 'http://localhost/Photostore/website/pri.php?gid=50&gal=y91mzu9o',,],
['Photos For John Doe (0)', 'http://localhost/Photostore/website/pri.php?gid=49&gal=bb5godcp',,],
['Animals & Insects (0)', 'http://localhost/Photostore/website/gallery.php?gid=29',,],
['Architecture (0)', 'http://localhost/Photostore/website/gallery.php?gid=30',,],
['Arts & Music (0)', 'http://localhost/Photostore/website/gallery.php?gid=31',,],
['Backgrounds (0)', 'http://localhost/Photostore/website/gallery.php?gid=32',,],
['Business & Office (0)', 'http://localhost/Photostore/website/gallery.php?gid=33',,],
['Food & Drink (0)', 'http://localhost/Photostore/website/gallery.php?gid=37',,],
['Holidays & Occasions (0)', 'http://localhost/Photostore/website/gallery.php?gid=38',,],
['Industry & Agriculture (0)', 'http://localhost/Photostore/website/gallery.php?gid=40',,],
['Landscapes & Nature (0)', 'http://localhost/Photostore/website/gallery.php?gid=41',,],
['Other (0)', 'http://localhost/Photostore/website/gallery.php?gid=47',,],
['People (0)', 'http://localhost/Photostore/website/gallery.php?gid=42',,],
['Signs & Symbols (0)', 'http://localhost/Photostore/website/gallery.php?gid=43',,],
['Space (0)', 'http://localhost/Photostore/website/gallery.php?gid=46',,],
['Sports & Recreation (0)', 'http://localhost/Photostore/website/gallery.php?gid=44',,],
['Technology (1)', 'http://localhost/Photostore/website/gallery.php?gid=36',,],
['Transportation (0)', 'http://localhost/Photostore/website/gallery.php?gid=45',,],
]
];